---
- hosts: local
  name: Automation of EC2 instance
  remote_user: root
  gather_facts: false
  tasks:
    - name: Create ec2
      amazon.aws.ec2_group:
       name: aws_instance_Ansible
       description: "ajeet-test security group"
       region: us-east-1
       rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
       rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
          
      register: firewall_sg
    - name: Create a new EC2 key
      ec2_key:
         name: "ajeet-test-key"
         region: "us-east-1"
         key_material: "{{ lookup('file', '/home/ajeet/.ssh/id_rsa.pub') }}"
    - name: Create an EC2 instance
      ec2:
         key_name: "ajeet-test-key"
         region: "us-east-1"
         group_id: "{{ firewall_sg.group_id }}"
         instance_type: "t2.micro"
         image: ami-0b0af3577fe5e3532 ## AMi for RHEL free tier vm
         wait: yes
         count_tag: Name
         exact_count: 1
         vpc_subnet_id: subnet-0a3aff513f0e62563
         assign_public_ip: yes
    - name : Add instance to host group
      add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
      loop: "{{ ec2.instances }}"
      
    - name: "refresh_inventory"
      meta: refresh_inventory
      
    - pause:
        minutes: 1  
  
  
- hosts: all

  gather_facts: no
  tasks:
  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
  - name: remove the Apache package
    dnf:
      name: httpd
      state: absent
  - name: Enable service to start on boot up
    dnf:
      name: httpd
      enablerepo: testing
      state: present
  - name: install latest version oa apache
    dnf:
      name: "*"
      state: latest
      
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted
         

     
          
